export * from './apikeys.service';
import { ApikeysService } from './apikeys.service';
export * from './aplicacionesExternas.service';
import { AplicacionesExternasService } from './aplicacionesExternas.service';
export * from './auditora.service';
import { AuditoraService } from './auditora.service';
export * from './autorizaciones.service';
import { AutorizacionesService } from './autorizaciones.service';
export * from './customForms.service';
import { CustomFormsService } from './customForms.service';
export * from './dashboards.service';
import { DashboardsService } from './dashboards.service';
export * from './dashboardsDeUsuarios.service';
import { DashboardsDeUsuariosService } from './dashboardsDeUsuarios.service';
export * from './estructuraOrganizativa.service';
import { EstructuraOrganizativaService } from './estructuraOrganizativa.service';
export * from './fuentesDeDatos.service';
import { FuentesDeDatosService } from './fuentesDeDatos.service';
export * from './grupos.service';
import { GruposService } from './grupos.service';
export * from './idiomas.service';
import { IdiomasService } from './idiomas.service';
export * from './integraciones.service';
import { IntegracionesService } from './integraciones.service';
export * from './interacciones.service';
import { InteraccionesService } from './interacciones.service';
export * from './parametrizacin.service';
import { ParametrizacinService } from './parametrizacin.service';
export * from './personas.service';
import { PersonasService } from './personas.service';
export * from './segments.service';
import { SegmentsService } from './segments.service';
export * from './solicitudes.service';
import { SolicitudesService } from './solicitudes.service';
export * from './tarjetaCiudadana.service';
import { TarjetaCiudadanaService } from './tarjetaCiudadana.service';
export * from './tiposDeSituaciones.service';
import { TiposDeSituacionesService } from './tiposDeSituaciones.service';
export * from './usersBusController.service';
import { UsersBusControllerService } from './usersBusController.service';
export * from './usuarios.service';
import { UsuariosService } from './usuarios.service';
export * from './widgets.service';
import { WidgetsService } from './widgets.service';
export const APIS = [ApikeysService, AplicacionesExternasService, AuditoraService, AutorizacionesService, CustomFormsService, DashboardsService, DashboardsDeUsuariosService, EstructuraOrganizativaService, FuentesDeDatosService, GruposService, IdiomasService, IntegracionesService, InteraccionesService, ParametrizacinService, PersonasService, SegmentsService, SolicitudesService, TarjetaCiudadanaService, TiposDeSituacionesService, UsersBusControllerService, UsuariosService, WidgetsService];
